### ISSUE TITLE
4.x手机，混淆后加载补丁报错Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by shinoko** [iReaderAndroid/ZeusPlugin#11]
demo里补丁同时修复了TestHotFixActivity和TestHotFix，混淆后也可修复成功

如果只修复TestHotFix，在没有混淆的情况下可以修复成功，混淆后会报如下错误：
E/AndroidRuntime(20525): FATAL EXCEPTION: main
E/AndroidRuntime(20525): java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
E/AndroidRuntime(20525):        at zeus.test.hotfix.TestHotFixActivity.onCreate(Unknown Source)
E/AndroidRuntime(20525):        at android.app.Activity.performCreate(Activity.java:5188)
E/AndroidRuntime(20525):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
E/AndroidRuntime(20525):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
E/AndroidRuntime(20525):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
E/AndroidRuntime(20525):        at android.app.ActivityThread.access$700(ActivityThread.java:140)
E/AndroidRuntime(20525):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
E/AndroidRuntime(20525):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20525):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(20525):        at android.app.ActivityThread.main(ActivityThread.java:4921)
E/AndroidRuntime(20525):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(20525):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(20525):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
E/AndroidRuntime(20525):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
E/AndroidRuntime(20525):        at dalvik.system.NativeStart.main(Native Method)

混淆有保持一致，插桩也成功了，不知道为什么还是会pre-verify……

**Comment by shinoko** [comment]
已解决，com.android.internal.util.Predicate这个类不能混淆

原因可参考http://blog.csdn.net/sbsujjbcy/article/details/51760578

**Comment by dazhiyu** [comment]
你好，问一下，是这个系统的类不能被混淆吗？还是与其相关的类不能混淆。

**Comment by dazhiyu** [comment]
@shinoko

**Comment by jimor1234567** [comment]
就这个类不能被混淆，其他都可以。
