### ISSUE TITLE
在插件里使用databinding找不到 ViewDataBinding

### ISSUE THREAD

**Issue by Hiram-Y** [iReaderAndroid/ZeusPlugin#14]
java.lang.RuntimeException: Unable to start activity ComponentInfo{zeus.test/com.zeus.ZeusActivityForStandard}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.databinding.ViewDataBinding.setVariable(int, java.lang.Object)' on a null object reference
                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:154)
                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by jimor1234567** [comment]
目前没有测试过对databinding的支持，需要自己调试一下看看问题在哪
