### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Harvey-Lin** [iReaderAndroid/ZeusPlugin#9]
Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
                                                               at dalvik.system.DexFile.defineClass(Native Method)
                                                               at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:211)
                                                               at dalvik.system.DexFile.loadClass(DexFile.java:200)
                                                               at zeus.plugin.ZeusPluginClassLoader.findClass(ZeusPluginClassLoader.java:179)
                                                               at zeus.plugin.ZeusPluginClassLoader.loadClass(ZeusPluginClassLoader.java:157)
                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:461)

**Comment by zshugithub** [comment]
重复引用包了。你查查插件里工程包的引用方式，是compile 还是 provided。

**Comment by Harvey-Lin** [comment]
引用方式provided

**Comment by jimor1234567** [comment]
请使用release打包方式来使用补丁，或者在android 4.4以上手机中debug调试补丁。

**Comment by shinoko** [comment]
引用provided，release打包，还是会报这个错
